[project]
name = "model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "numpy>=1.26.0",
    "onnx>=1.16.0",
    "onnx2tf>=1.25.0",
    "onnxscript>=0.1.0",
    "onnxslim>=0.1.31",
    "onnx-graphsurgeon>=0.5.5",
    "tf-keras>=2.16.0",
    "psutil>=5.9.0",
    "tqdm>=4.66.0",
    "ai-edge-litert>=1.0.1",
    "onnx-simplifier>=0.4.36",
    "simple-onnx-processing-tools>=1.1.0",
    "sng4onnx>=1.0.1",
    "snc4onnx>=1.0.1",
    "snd4onnx>=1.1.2",
    "sne4onnx>=1.0.1",
    "scs4onnx>=1.0.1",
    "sit4onnx>=1.0.1",
    "sam4onnx>=1.0.1",
    "sor4onnx>=1.0.0",
    "pillow>=10.0.0",
    "tensorflow>=2.16.1",
    "torch>=2.2.0",
    "torchvision>=0.17.0",
    "pyserial>=3.5",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]
torchvision = [
  { index = "pytorch-cpu" },
]
